const PREFIX = '@EXAMPLE';

export const SET_EXAMPLE = `${PREFIX}/SET_EXAMPLE`;
export const SET_EXAMPLE_SELECTED_ID = `${PREFIX}/SET_EXAMPLE_SELECTED_ID`;
export const SET_EXAMPLE_LOADING = `${PREFIX}/SET_EXAMPLE_LOADING`;